---
name: Catalyst-Plugin-Cache-Store-FastMmap
version: 0.01
author:
  - 'Yuval Kogman, C<nothingmuch@woobling.org>'
abstract: |-
  FastMmap cache store for
  L<Catalyst::Plugin::Cache>.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Cache::FastMmap: 0
  Catalyst: 5.7
  Catalyst::Plugin::Cache: 0.01
  Path::Class: 0
provides:
  Catalyst::Plugin::Cache::Backend::FastMmap:
    file: lib/Catalyst/Plugin/Cache/Backend/FastMmap.pm
  Catalyst::Plugin::Cache::Store::FastMmap:
    file: lib/Catalyst/Plugin/Cache/Store/FastMmap.pm
    version: 0.01
generated_by: Module::Build version 0.2801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
