--- #YAML:1.0
name:                Catalyst-Plugin-Cache-Store-FastMmap
version:             0.02
abstract:            ~
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Cache::FastMmap:               0
    Catalyst:                      5.7
    Catalyst::Plugin::Cache:       0.01
    Path::Class:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
